// Lazy-loaded brand icons, keyed by the name used in blueprints and drawers.
export const lazyIconsMapping = {
  Alpaca: () => import("./BRAND_ICONS/Alpaca"),
  Anthropic: () => import("./BRAND_ICONS/Anthropic"),
  Google: () => import("./BRAND_ICONS/Google"),
  GoogleSearch: () => import("./BRAND_ICONS/GoogleSearch"),
  GoogleGemini: () => import("./BRAND_ICONS/GoogleGemini"),
  HyperLiquid: () => import("./BRAND_ICONS/HyperLiquid"),
  Polymarket: () => import("./BRAND_ICONS/Polymarket"),
  Kalshi: () => import("./BRAND_ICONS/Kalshi"),
  Massive: () => import("./BRAND_ICONS/Massive"),
  MySQL: () => import("./BRAND_ICONS/MySQL"),
  MongoDB: () => import("./BRAND_ICONS/MongoDB"),
  OpenAI: () => import("./BRAND_ICONS/OpenAi"),
  OpenRouter: () => import("./BRAND_ICONS/OpenRouter"),
  Postgres: () => import("./BRAND_ICONS/Postgres"),
  Redis: () => import("./BRAND_ICONS/Redis"),
  Tavily: () => import("./BRAND_ICONS/Tavily"),
  Uniswap: () => import("./BRAND_ICONS/Uniswap"),
  xAI: () => import("./BRAND_ICONS/xAI"),
  Grok: () => import("./BRAND_ICONS/Grok"),
};
