// Lazy-loaded brand icons, keyed by the name used in blueprints and drawers.
export const lazyIconsMapping = {
  Alpaca: () => import("./integrations/Alpaca"),
  Anthropic: () => import("./integrations/Anthropic"),
  Google: () => import("./integrations/Google"),
  GoogleSearch: () => import("./integrations/GoogleSearch"),
  GoogleGemini: () => import("./integrations/GoogleGemini"),
  HyperLiquid: () => import("./integrations/HyperLiquid"),
  Polymarket: () => import("./integrations/Polymarket"),
  Kalshi: () => import("./integrations/Kalshi"),
  Massive: () => import("./integrations/Massive"),
  MySQL: () => import("./integrations/MySQL"),
  MongoDB: () => import("./integrations/MongoDB"),
  OpenAI: () => import("./integrations/OpenAI"),
  OpenRouter: () => import("./integrations/OpenRouter"),
  Postgres: () => import("./integrations/Postgres"),
  Redis: () => import("./integrations/Redis"),
  Tavily: () => import("./integrations/Tavily"),
  Uniswap: () => import("./integrations/Uniswap"),
  xAI: () => import("./integrations/xAI"),
  Grok: () => import("./integrations/Grok"),
};
