import { Shelf } from "../types/Shelf"

export const CORE_DRAWERS = {
  saved_components:    { displayName: "Saved",              id: "saved_components",    icon: "GradientSave" },
  input_output:        { displayName: "Input & Output",     id: "input_output",        icon: "Cable" },
  data_source:         { displayName: "Data Sources",       id: "data_source",         icon: "Database" },
  models_and_agents:   { displayName: "Models & Agents",    id: "models_and_agents",   icon: "Bot" },
  llm_operations:      { displayName: "LLM Operations",     id: "llm_operations",      icon: "BrainCircuit" },
  files_and_knowledge: { displayName: "Files & Knowledge",  id: "files_and_knowledge", icon: "Layers" },
  processing:          { displayName: "Processing",         id: "processing",          icon: "ListFilter" },
  flow_controls:       { displayName: "Flow Controls",      id: "flow_controls",       icon: "ArrowRightLeft" },
  utilities:           { displayName: "Utilities",          id: "utilities",           icon: "Wand2" },
  prototypes:          { displayName: "Prototypes",         id: "prototypes",          icon: "FlaskConical" },
  tools:               { displayName: "Tools",              id: "tools",               icon: "Hammer" },
} as const as Record<Shelf.Drawer.Id, Shelf.Drawer>

export const BUNDLE_DRAWERS = {
  aiml:              { displayName: "AI/ML API",           id: "aiml",              icon: "AIML" },
  agentql:           { displayName: "AgentQL",             id: "agentql",           icon: "AgentQL" },
  altk:              { displayName: "ALTK",                id: "altk",              icon: "Zap" },
  languagemodels:    { displayName: "Language Models",     id: "languagemodels",    icon: "BrainCircuit" },
  embeddings:        { displayName: "Embeddings",          id: "embeddings",        icon: "Binary" },
  amazon:            { displayName: "Amazon",              id: "amazon",            icon: "Amazon" },
  anthropic:         { displayName: "Anthropic",           id: "anthropic",         icon: "Anthropic" },
  apify:             { displayName: "Apify",               id: "apify",             icon: "Apify" },
  arxiv:             { displayName: "arXiv",               id: "arxiv",             icon: "arXiv" },
  assemblyai:        { displayName: "AssemblyAI",          id: "assemblyai",        icon: "AssemblyAI" },
  azure:             { displayName: "Azure",               id: "azure",             icon: "Azure" },
  baidu:             { displayName: "Baidu",               id: "baidu",             icon: "BaiduQianfan" },
  bing:              { displayName: "Bing",                id: "bing",              icon: "Bing" },
  cassandra:         { displayName: "Cassandra",           id: "cassandra",         icon: "Cassandra" },
  chroma:            { displayName: "Chroma",              id: "chroma",            icon: "Chroma" },
  clickhouse:        { displayName: "ClickHouse",          id: "clickhouse",        icon: "Clickhouse" },
  cleanlab:          { displayName: "Cleanlab",            id: "cleanlab",          icon: "Cleanlab" },
  cloudflare:        { displayName: "Cloudflare",          id: "cloudflare",        icon: "Cloudflare" },
  cohere:            { displayName: "Cohere",              id: "cohere",            icon: "Cohere" },
  cometapi:          { displayName: "CometAPI",            id: "cometapi",          icon: "CometAPI" },
  composio:          { displayName: "Composio",            id: "composio",          icon: "Composio" },
  confluence:        { displayName: "Confluence",          id: "confluence",        icon: "Confluence" },
  couchbase:         { displayName: "Couchbase",           id: "couchbase",         icon: "Couchbase" },
  crewai:            { displayName: "CrewAI",              id: "crewai",            icon: "CrewAI" },
  cuga:              { displayName: "CUGA",                id: "cuga",              icon: "Bot" },
  datastax:          { displayName: "DataStax",            id: "datastax",          icon: "AstraDB" },
  deepseek:          { displayName: "DeepSeek",            id: "deepseek",          icon: "DeepSeek" },
  docling:           { displayName: "Docling",             id: "docling",           icon: "Docling" },
  duckduckgo:        { displayName: "DuckDuckGo",          id: "duckduckgo",        icon: "DuckDuckGo" },
  elastic:           { displayName: "Elastic",             id: "elastic",           icon: "ElasticsearchStore" },
  exa:               { displayName: "Exa",                 id: "exa",               icon: "Exa" },
  FAISS:             { displayName: "FAISS",               id: "FAISS",             icon: "FAISS" },
  firecrawl:         { displayName: "Firecrawl",           id: "firecrawl",         icon: "FirecrawlCrawlApi" },
  git:               { displayName: "Git",                 id: "git",               icon: "GitLoader" },
  glean:             { displayName: "Glean",               id: "glean",             icon: "Glean" },
  gmail:             { displayName: "Gmail",               id: "gmail",             icon: "Gmail" },
  google:            { displayName: "Google",              id: "google",            icon: "Google" },
  groq:              { displayName: "Groq",                id: "groq",              icon: "Groq" },
  homeassistant:     { displayName: "Home Assistant",      id: "homeassistant",     icon: "HomeAssistant" },
  huggingface:       { displayName: "Hugging Face",        id: "huggingface",       icon: "HuggingFace" },
  ibm:               { displayName: "IBM",                 id: "ibm",               icon: "WatsonxAI" },
  icosacomputing:    { displayName: "Icosa Computing",     id: "icosacomputing",    icon: "Icosa" },
  jigsawstack:       { displayName: "JigsawStack",         id: "jigsawstack",       icon: "JigsawStack" },
  langchain_utils:   { displayName: "LangChain",           id: "langchain_utils",   icon: "LangChain" },
  langwatch:         { displayName: "LangWatch",           id: "langwatch",         icon: "Langwatch" },
  lmstudio:          { displayName: "LMStudio",            id: "lmstudio",          icon: "LMStudio" },
  maritalk:          { displayName: "MariTalk",            id: "maritalk",          icon: "Maritalk" },
  mem0:              { displayName: "Mem0",                id: "mem0",              icon: "Mem0" },
  memories:          { displayName: "Memories",            id: "memories",          icon: "Cpu" },
  milvus:            { displayName: "Milvus",              id: "milvus",            icon: "Milvus" },
  mistral:           { displayName: "MistralAI",           id: "mistral",           icon: "MistralAI" },
  mongodb:           { displayName: "MongoDB",             id: "mongodb",           icon: "MongoDB" },
  needle:            { displayName: "Needle",              id: "needle",            icon: "Needle" },
  notdiamond:        { displayName: "Not Diamond",         id: "notdiamond",        icon: "NotDiamond" },
  notion:            { displayName: "Notion",              id: "Notion",            icon: "Notion" },
  novita:            { displayName: "Novita",              id: "novita",            icon: "Novita" },
  nvidia:            { displayName: "NVIDIA",              id: "nvidia",            icon: "NVIDIA" },
  olivya:            { displayName: "Olivya",              id: "olivya",            icon: "Olivya" },
  ollama:            { displayName: "Ollama",              id: "ollama",            icon: "Ollama" },
  openai:            { displayName: "OpenAI",              id: "openai",            icon: "OpenAI" },
  openrouter:        { displayName: "OpenRouter",          id: "openrouter",        icon: "OpenRouter" },
  perplexity:        { displayName: "Perplexity",          id: "perplexity",        icon: "Perplexity" },
  pgvector:          { displayName: "pgvector",            id: "pgvector",          icon: "cpu" },
  pinecone:          { displayName: "Pinecone",            id: "pinecone",          icon: "Pinecone" },
  qdrant:            { displayName: "Qdrant",              id: "qdrant",            icon: "Qdrant" },
  redis:             { displayName: "Redis",               id: "redis",             icon: "Redis" },
  sambanova:         { displayName: "SambaNova",           id: "sambanova",         icon: "SambaNova" },
  scrapegraph:       { displayName: "ScrapeGraph AI",      id: "scrapegraph",       icon: "ScrapeGraph" },
  searchapi:         { displayName: "SearchApi",           id: "searchapi",         icon: "SearchAPI" },
  serpapi:           { displayName: "SerpApi",             id: "serpapi",           icon: "SerpSearch" },
  serper:            { displayName: "Serper",              id: "serper",            icon: "Serper" },
  supabase:          { displayName: "Supabase",            id: "supabase",          icon: "Supabase" },
  tavily:            { displayName: "Tavily",              id: "tavily",            icon: "TavilyIcon" },
  twelvelabs:        { displayName: "TwelveLabs",          id: "twelvelabs",        icon: "TwelveLabs" },
  unstructured:      { displayName: "Unstructured",        id: "unstructured",      icon: "Unstructured" },
  upstash:           { displayName: "Upstash",             id: "upstash",           icon: "Upstash" },
  vlmrun:            { displayName: "VLM Run",             id: "vlmrun",            icon: "VLMRun" },
  vectara:           { displayName: "Vectara",             id: "vectara",           icon: "Vectara" },
  vectorstores:      { displayName: "Vector Stores",       id: "vectorstores",      icon: "Layers" },
  weaviate:          { displayName: "Weaviate",            id: "weaviate",          icon: "Weaviate" },
  vertexai:          { displayName: "Vertex AI",           id: "vertexai",          icon: "VertexAI" },
  wikipedia:         { displayName: "Wikipedia",           id: "wikipedia",         icon: "Wikipedia" },
  wolframalpha:      { displayName: "WolframAlpha",        id: "wolframalpha",      icon: "WolframAlphaAPI" },
  xai:               { displayName: "xAI",                 id: "xai",               icon: "xAI" },
  yahoosearch:       { displayName: "Yahoo! Finance",      id: "yahoosearch",       icon: "trending-up" },
  youtube:           { displayName: "YouTube",             id: "youtube",           icon: "YouTube" },
  zep:               { displayName: "Zep",                 id: "zep",               icon: "ZepMemory" },
} as const as Record<Shelf.Drawer.Id, Shelf.Drawer>

export const ALL_DRAWERS = { ...CORE_DRAWERS, ...BUNDLE_DRAWERS } as const

export const SECTIONS = {
  core: Object.keys(CORE_DRAWERS) as Shelf.Drawer.Id[],
  bundles: Object.keys(BUNDLE_DRAWERS) as Shelf.Drawer.Id[],
} as const