/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiPreviewIndexRouteImport } from './routes/ui-preview/index'
import { Route as IconsPreviewIndexRouteImport } from './routes/icons-preview/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as WorkflowWorkflowidRouteImport } from './routes/workflow/$workflowid'
import { Route as HomeUsageRouteImport } from './routes/home/usage'
import { Route as HomeTemplatesRouteImport } from './routes/home/templates'
import { Route as HomeSettingsRouteImport } from './routes/home/settings'
import { Route as HomeLibraryRouteImport } from './routes/home/library'
import { Route as HomeExecutionsRouteImport } from './routes/home/executions'
import { Route as HomeCredentialsRouteImport } from './routes/home/credentials'
import { Route as HomeLibraryIndexRouteImport } from './routes/home/library/index'
import { Route as HomeLibraryFolderIdRouteImport } from './routes/home/library/$folderId'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiPreviewIndexRoute = UiPreviewIndexRouteImport.update({
  id: '/ui-preview/',
  path: '/ui-preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsPreviewIndexRoute = IconsPreviewIndexRouteImport.update({
  id: '/icons-preview/',
  path: '/icons-preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowWorkflowidRoute = WorkflowWorkflowidRouteImport.update({
  id: '/workflow/$workflowid',
  path: '/workflow/$workflowid',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeUsageRoute = HomeUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => HomeRoute,
} as any)
const HomeTemplatesRoute = HomeTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => HomeRoute,
} as any)
const HomeSettingsRoute = HomeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HomeRoute,
} as any)
const HomeLibraryRoute = HomeLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => HomeRoute,
} as any)
const HomeExecutionsRoute = HomeExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => HomeRoute,
} as any)
const HomeCredentialsRoute = HomeCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => HomeRoute,
} as any)
const HomeLibraryIndexRoute = HomeLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeLibraryRoute,
} as any)
const HomeLibraryFolderIdRoute = HomeLibraryFolderIdRouteImport.update({
  id: '/$folderId',
  path: '/$folderId',
  getParentRoute: () => HomeLibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/home/credentials': typeof HomeCredentialsRoute
  '/home/executions': typeof HomeExecutionsRoute
  '/home/library': typeof HomeLibraryRouteWithChildren
  '/home/settings': typeof HomeSettingsRoute
  '/home/templates': typeof HomeTemplatesRoute
  '/home/usage': typeof HomeUsageRoute
  '/workflow/$workflowid': typeof WorkflowWorkflowidRoute
  '/auth/': typeof AuthIndexRoute
  '/home/': typeof HomeIndexRoute
  '/icons-preview/': typeof IconsPreviewIndexRoute
  '/ui-preview/': typeof UiPreviewIndexRoute
  '/home/library/$folderId': typeof HomeLibraryFolderIdRoute
  '/home/library/': typeof HomeLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home/credentials': typeof HomeCredentialsRoute
  '/home/executions': typeof HomeExecutionsRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/templates': typeof HomeTemplatesRoute
  '/home/usage': typeof HomeUsageRoute
  '/workflow/$workflowid': typeof WorkflowWorkflowidRoute
  '/auth': typeof AuthIndexRoute
  '/home': typeof HomeIndexRoute
  '/icons-preview': typeof IconsPreviewIndexRoute
  '/ui-preview': typeof UiPreviewIndexRoute
  '/home/library/$folderId': typeof HomeLibraryFolderIdRoute
  '/home/library': typeof HomeLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/home/credentials': typeof HomeCredentialsRoute
  '/home/executions': typeof HomeExecutionsRoute
  '/home/library': typeof HomeLibraryRouteWithChildren
  '/home/settings': typeof HomeSettingsRoute
  '/home/templates': typeof HomeTemplatesRoute
  '/home/usage': typeof HomeUsageRoute
  '/workflow/$workflowid': typeof WorkflowWorkflowidRoute
  '/auth/': typeof AuthIndexRoute
  '/home/': typeof HomeIndexRoute
  '/icons-preview/': typeof IconsPreviewIndexRoute
  '/ui-preview/': typeof UiPreviewIndexRoute
  '/home/library/$folderId': typeof HomeLibraryFolderIdRoute
  '/home/library/': typeof HomeLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/home/credentials'
    | '/home/executions'
    | '/home/library'
    | '/home/settings'
    | '/home/templates'
    | '/home/usage'
    | '/workflow/$workflowid'
    | '/auth/'
    | '/home/'
    | '/icons-preview/'
    | '/ui-preview/'
    | '/home/library/$folderId'
    | '/home/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home/credentials'
    | '/home/executions'
    | '/home/settings'
    | '/home/templates'
    | '/home/usage'
    | '/workflow/$workflowid'
    | '/auth'
    | '/home'
    | '/icons-preview'
    | '/ui-preview'
    | '/home/library/$folderId'
    | '/home/library'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/home/credentials'
    | '/home/executions'
    | '/home/library'
    | '/home/settings'
    | '/home/templates'
    | '/home/usage'
    | '/workflow/$workflowid'
    | '/auth/'
    | '/home/'
    | '/icons-preview/'
    | '/ui-preview/'
    | '/home/library/$folderId'
    | '/home/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
  WorkflowWorkflowidRoute: typeof WorkflowWorkflowidRoute
  AuthIndexRoute: typeof AuthIndexRoute
  IconsPreviewIndexRoute: typeof IconsPreviewIndexRoute
  UiPreviewIndexRoute: typeof UiPreviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-preview/': {
      id: '/ui-preview/'
      path: '/ui-preview'
      fullPath: '/ui-preview/'
      preLoaderRoute: typeof UiPreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icons-preview/': {
      id: '/icons-preview/'
      path: '/icons-preview'
      fullPath: '/icons-preview/'
      preLoaderRoute: typeof IconsPreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$workflowid': {
      id: '/workflow/$workflowid'
      path: '/workflow/$workflowid'
      fullPath: '/workflow/$workflowid'
      preLoaderRoute: typeof WorkflowWorkflowidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/usage': {
      id: '/home/usage'
      path: '/usage'
      fullPath: '/home/usage'
      preLoaderRoute: typeof HomeUsageRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/templates': {
      id: '/home/templates'
      path: '/templates'
      fullPath: '/home/templates'
      preLoaderRoute: typeof HomeTemplatesRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/settings': {
      id: '/home/settings'
      path: '/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeSettingsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/library': {
      id: '/home/library'
      path: '/library'
      fullPath: '/home/library'
      preLoaderRoute: typeof HomeLibraryRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/executions': {
      id: '/home/executions'
      path: '/executions'
      fullPath: '/home/executions'
      preLoaderRoute: typeof HomeExecutionsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/credentials': {
      id: '/home/credentials'
      path: '/credentials'
      fullPath: '/home/credentials'
      preLoaderRoute: typeof HomeCredentialsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/library/': {
      id: '/home/library/'
      path: '/'
      fullPath: '/home/library/'
      preLoaderRoute: typeof HomeLibraryIndexRouteImport
      parentRoute: typeof HomeLibraryRoute
    }
    '/home/library/$folderId': {
      id: '/home/library/$folderId'
      path: '/$folderId'
      fullPath: '/home/library/$folderId'
      preLoaderRoute: typeof HomeLibraryFolderIdRouteImport
      parentRoute: typeof HomeLibraryRoute
    }
  }
}

interface HomeLibraryRouteChildren {
  HomeLibraryFolderIdRoute: typeof HomeLibraryFolderIdRoute
  HomeLibraryIndexRoute: typeof HomeLibraryIndexRoute
}

const HomeLibraryRouteChildren: HomeLibraryRouteChildren = {
  HomeLibraryFolderIdRoute: HomeLibraryFolderIdRoute,
  HomeLibraryIndexRoute: HomeLibraryIndexRoute,
}

const HomeLibraryRouteWithChildren = HomeLibraryRoute._addFileChildren(
  HomeLibraryRouteChildren,
)

interface HomeRouteChildren {
  HomeCredentialsRoute: typeof HomeCredentialsRoute
  HomeExecutionsRoute: typeof HomeExecutionsRoute
  HomeLibraryRoute: typeof HomeLibraryRouteWithChildren
  HomeSettingsRoute: typeof HomeSettingsRoute
  HomeTemplatesRoute: typeof HomeTemplatesRoute
  HomeUsageRoute: typeof HomeUsageRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeCredentialsRoute: HomeCredentialsRoute,
  HomeExecutionsRoute: HomeExecutionsRoute,
  HomeLibraryRoute: HomeLibraryRouteWithChildren,
  HomeSettingsRoute: HomeSettingsRoute,
  HomeTemplatesRoute: HomeTemplatesRoute,
  HomeUsageRoute: HomeUsageRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
  WorkflowWorkflowidRoute: WorkflowWorkflowidRoute,
  AuthIndexRoute: AuthIndexRoute,
  IconsPreviewIndexRoute: IconsPreviewIndexRoute,
  UiPreviewIndexRoute: UiPreviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
