/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiPreviewIndexRouteImport } from './routes/ui-preview/index'
import { Route as IconsPreviewIndexRouteImport } from './routes/icons-preview/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as WorkflowWorkflowidRouteImport } from './routes/workflow/$workflowid'
import { Route as WorkflowWorkflowidIndexRouteImport } from './routes/workflow/$workflowid/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiPreviewIndexRoute = UiPreviewIndexRouteImport.update({
  id: '/ui-preview/',
  path: '/ui-preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsPreviewIndexRoute = IconsPreviewIndexRouteImport.update({
  id: '/icons-preview/',
  path: '/icons-preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowWorkflowidRoute = WorkflowWorkflowidRouteImport.update({
  id: '/workflow/$workflowid',
  path: '/workflow/$workflowid',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowWorkflowidIndexRoute = WorkflowWorkflowidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowWorkflowidRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workflow/$workflowid': typeof WorkflowWorkflowidRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/icons-preview/': typeof IconsPreviewIndexRoute
  '/ui-preview/': typeof UiPreviewIndexRoute
  '/workflow/$workflowid/': typeof WorkflowWorkflowidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/icons-preview': typeof IconsPreviewIndexRoute
  '/ui-preview': typeof UiPreviewIndexRoute
  '/workflow/$workflowid': typeof WorkflowWorkflowidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workflow/$workflowid': typeof WorkflowWorkflowidRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/icons-preview/': typeof IconsPreviewIndexRoute
  '/ui-preview/': typeof UiPreviewIndexRoute
  '/workflow/$workflowid/': typeof WorkflowWorkflowidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workflow/$workflowid'
    | '/auth/'
    | '/icons-preview/'
    | '/ui-preview/'
    | '/workflow/$workflowid/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/icons-preview' | '/ui-preview' | '/workflow/$workflowid'
  id:
    | '__root__'
    | '/'
    | '/workflow/$workflowid'
    | '/auth/'
    | '/icons-preview/'
    | '/ui-preview/'
    | '/workflow/$workflowid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkflowWorkflowidRoute: typeof WorkflowWorkflowidRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  IconsPreviewIndexRoute: typeof IconsPreviewIndexRoute
  UiPreviewIndexRoute: typeof UiPreviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-preview/': {
      id: '/ui-preview/'
      path: '/ui-preview'
      fullPath: '/ui-preview/'
      preLoaderRoute: typeof UiPreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icons-preview/': {
      id: '/icons-preview/'
      path: '/icons-preview'
      fullPath: '/icons-preview/'
      preLoaderRoute: typeof IconsPreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$workflowid': {
      id: '/workflow/$workflowid'
      path: '/workflow/$workflowid'
      fullPath: '/workflow/$workflowid'
      preLoaderRoute: typeof WorkflowWorkflowidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$workflowid/': {
      id: '/workflow/$workflowid/'
      path: '/'
      fullPath: '/workflow/$workflowid/'
      preLoaderRoute: typeof WorkflowWorkflowidIndexRouteImport
      parentRoute: typeof WorkflowWorkflowidRoute
    }
  }
}

interface WorkflowWorkflowidRouteChildren {
  WorkflowWorkflowidIndexRoute: typeof WorkflowWorkflowidIndexRoute
}

const WorkflowWorkflowidRouteChildren: WorkflowWorkflowidRouteChildren = {
  WorkflowWorkflowidIndexRoute: WorkflowWorkflowidIndexRoute,
}

const WorkflowWorkflowidRouteWithChildren =
  WorkflowWorkflowidRoute._addFileChildren(WorkflowWorkflowidRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkflowWorkflowidRoute: WorkflowWorkflowidRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  IconsPreviewIndexRoute: IconsPreviewIndexRoute,
  UiPreviewIndexRoute: UiPreviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
